return {
--     "xiyaowong/transparent.nvim",
-- 		lazy = false,
--     -- reformular las transparencias en
--     -- :TransparentEnable
--     -- :TransparentDisable
--     -- :TransparentToggle
--     config = function()
--         require("transparent").setup({
--             groups = {
--                 'Normal', 'NormalNC', 'Comment', 'Constant', 'Special', 'Identifier',
--                 'Statement', 'PreProc', 'Type', 'Underlined', 'Todo', 'String', 'Function',
--                 'Conditional', 'Repeat', 'Operator', 'Structure', 'LineNr', 'NonText',
--                 'SignColumn', 'CursorLine', 'CursorLineNr', 'StatusLine', 'StatusLineNC',
--                 'EndOfBuffer',
--             },
--             extra_groups = {
--                 "NormalFloat", "SignColumn", "LineNr", "CursorLine", "CursorLineNr", "VertSplit",
--                 "StatusLine", "TabLine", "TabLineFill", "TabLineSel", "Pmenu", "WinSeparator",
--                 "NeoTreeNormal", "NeoTreeNormalNC", "TelescopeNormal", "TelescopeBorder",
--                 "FloatBorder", "NvimTreeNormal",
--             },
--             exclude_groups = {},
--         })
--
--         -- Mapeos de teclas
--         vim.keymap.set('n', '<leader>te', ":TransparentEnable<CR>", { desc = "Enable transparency" })
--         vim.keymap.set('n', '<leader>tn', ":TransparentDisable<CR>", { desc = "Disable transparency" })
--         vim.keymap.set('n', '<leader>tt', ":TransparentToggle<CR>", { desc = "Toggle transparency" })
--     end,
}
--
